#!/usr/bin/python2
from sys import argv
import numpy as np
from pyAudioAnalysis import audioTrainTest as aT

script, filename = argv
isSignificant = 0.7

Result, P, classNames = aT.fileClassification(filename, "svmModel", "svm")
winner = np.argmax(P)

if P[winner] > isSignificant :
    print("File: " + filename + " is in category: " + classNames[winner])
else :
    print("Sound classification not certain: ")

print(str(P))
